# Generated by Django 5.2.9 on 2025-12-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=50)),
                ('cafe_manha', models.CharField(max_length=200)),
                ('almoco', models.CharField(max_length=200)),
                ('lanche_tarde', models.CharField(max_length=200)),
            ],
        ),
    ]
